function paint_data(~,~,hfig)

HotBirdProp=get(hfig,'userdata');
[~,cnmax] = size(HotBirdProp.cs.s);

scrsz=HotBirdProp.scrsz;
sidy=scrsz(4)/2;
sidx=0.65*sidy;
hfig5=figure('position',[scrsz(4)/1.0 scrsz(3)/12 sidx sidy]);
set(hfig5,'Name','Bundle data');
set(hfig5,'color',[.99 .99 .99]);
set(hfig5,'Menubar','none');
set(hfig5,'numbertitle','off');
set(hfig5,'userdata',HotBirdProp);

%% Fuel data:
HotBirdProp.handles.data_text1=annotation(hfig5,'textbox',[0.03 0.92 0.23 0.05], ...
    'string','Fuel data:','fontweight','bold','LineStyle','none');
set(HotBirdProp.handles.data_text1,'LineStyle','none');
set(HotBirdProp.handles.data_text1,'FontWeight','bold');
set(HotBirdProp.handles.data_text1,'FontSize',11);
set(HotBirdProp.handles.data_text1, 'FontUnits', 'normalized');
set(HotBirdProp.handles.data_text1,'BackgroundColor', [0.99,0.99,0.99]);
%% Fuel type
ce = char(HotBirdProp.cs.s(HotBirdProp.cn).type);
HotBirdProp.handles.data_text2=annotation(hfig5,'textbox',[0.265 0.92 0.32 0.05], ...
    'string',ce,'fontweight','bold','LineStyle','none');
set(HotBirdProp.handles.data_text2,'LineStyle','none');
set(HotBirdProp.handles.data_text2,'FontWeight','bold');
set(HotBirdProp.handles.data_text2,'FontSize',11);
set(HotBirdProp.handles.data_text2, 'FontUnits', 'normalized');
set(HotBirdProp.handles.data_text2,'BackgroundColor', [0.99,0.99,0.99]);
%%  Pellets button
HotBirdProp.handles.caxfile=uicontrol (hfig5,'style', 'pushbutton', 'string','Pellets','FontWeight','bold', ...
    'units','Normalized','position', [0.60 0.92 0.17 0.05], 'callback',{@pellets_data,hfig});
set(HotBirdProp.handles.caxfile,'FontWeight','bold');
set(HotBirdProp.handles.caxfile,'FontSize',11);
set(HotBirdProp.handles.caxfile, 'FontUnits', 'normalized');
set(HotBirdProp.handles.caxfile','BackgroundColor', [0.96,0.96,0.96]);
%%  Rods button
HotBirdProp.handles.caxfile=uicontrol (hfig5,'style', 'pushbutton', 'string','Rods','FontWeight','bold', ...
    'units','Normalized','position', [0.78 0.92 0.17 0.05], 'callback',{@rods_data,hfig});
set(HotBirdProp.handles.caxfile,'FontWeight','bold');
set(HotBirdProp.handles.caxfile,'FontSize',11);
set(HotBirdProp.handles.caxfile, 'FontUnits', 'normalized');
set(HotBirdProp.handles.caxfile','BackgroundColor', [0.96,0.96,0.96]);
%%  Write BTF file button
HotBirdProp.handles.caxfile=uicontrol (hfig5,'style', 'pushbutton', 'string','Write BTF file','FontWeight','bold', ...
    'units','Normalized','position', [0.63 0.86 0.30 0.05], 'callback',{@write_btf_file,hfig});
set(HotBirdProp.handles.caxfile,'FontWeight','bold');
set(HotBirdProp.handles.caxfile,'FontSize',11);
set(HotBirdProp.handles.caxfile, 'FontUnits', 'normalized');
set(HotBirdProp.handles.caxfile','BackgroundColor', [0.96,0.96,0.96]);



HotBirdProp.handles.data=axes('position',[0.10 0.10 0.8 0.8]);
set(gca,'XTick',[],'YTick',[]);
set(gca,'color', [0.99,0.99,0.99]);
set(gca,'XColor','white');





set(hfig,'userdata',HotBirdProp);
end





function pellets_data(~,~,hfig)

HotBirdProp=get(hfig,'userdata');
axes(HotBirdProp.handles.data);
cla;

for k=1:HotBirdProp.cs.cnmax
    HotBirdProp.cs.s(k).number_enrichments;
end

ce=sprintf('Number of pellets');
text(0.05, 0.95, ce,...
    'Color', 'black',...
    'FontSize', 11,...
    'FontUnits', 'normalized',...
    'FontWeight', 'bold',...
    'VerticalAlignment', 'middle',...
    'BackgroundColor', [0.99,0.99,0.99],...
    'HorizontalAlignment', 'left');
ce=sprintf('Number');
text(0.05, 0.85, ce,...
    'Color', 'black',...
    'FontSize', 11,...
    'FontUnits', 'normalized',...
    'FontWeight', 'bold',...
    'VerticalAlignment', 'middle',...
    'BackgroundColor', [0.99,0.99,0.99],...
    'HorizontalAlignment', 'left');
ce=sprintf('U235');
text(0.30, 0.85, ce,...
    'Color', 'black',...
    'FontSize', 11,...
    'FontUnits', 'normalized',...
    'FontWeight', 'bold',...
    'VerticalAlignment', 'middle',...
    'BackgroundColor', [0.99,0.99,0.99],...
    'HorizontalAlignment', 'left');
ce=sprintf('BA');
text(0.55, 0.85, ce,...
    'Color', 'black',...
    'FontSize', 11,...
    'FontUnits', 'normalized',...
    'FontWeight', 'bold',...
    'VerticalAlignment', 'middle',...
    'BackgroundColor', [0.99,0.99,0.99],...
    'HorizontalAlignment', 'left');

for k=1:HotBirdProp.cs.s(HotBirdProp.cn).nr_fue
    ce=sprintf('%4.0f',HotBirdProp.cs.s(HotBirdProp.cn).nr_enr(k));
    text(0.05, 0.85-0.04*k, ce,...
        'Color', 'black',...
        'FontSize', 11,...
        'FontUnits', 'normalized',...
        'FontWeight', 'bold',...
        'VerticalAlignment', 'middle',...
        'BackgroundColor', [0.99,0.99,0.99],...
        'HorizontalAlignment', 'left');
end

for k=1:HotBirdProp.cs.s(HotBirdProp.cn).nr_fue
    ce=sprintf('%5.2f',HotBirdProp.cs.s(HotBirdProp.cn).fue(k,3));
    text(0.30, 0.85-0.04*k, ce,...
        'Color', 'black',...
        'FontSize', 11,...
        'FontUnits', 'normalized',...
        'FontWeight', 'bold',...
        'VerticalAlignment', 'middle',...
        'BackgroundColor', [0.99,0.99,0.99],...
        'HorizontalAlignment', 'left');
end

for k=1:HotBirdProp.cs.s(HotBirdProp.cn).nr_fue
    ce=sprintf('%5.2f',HotBirdProp.cs.s(HotBirdProp.cn).fue(k,5));
    if(~isnan(HotBirdProp.cs.s(HotBirdProp.cn).fue(k,5)))
        text(0.55, 0.85-0.04*k, ce,...
            'Color', 'black',...
            'FontSize', 11,...
            'FontUnits', 'normalized',...
            'FontWeight', 'bold',...
            'VerticalAlignment', 'middle',...
            'BackgroundColor', [0.99,0.99,0.99],...
            'HorizontalAlignment', 'left');
    end
end

ce=sprintf('Total Number');
text(0.05, 0.85-0.04*HotBirdProp.cs.s(HotBirdProp.cn).nr_fue-0.10, ce,...
    'Color', 'black',...
    'FontSize', 11,...
    'FontUnits', 'normalized',...
    'FontWeight', 'bold',...
    'VerticalAlignment', 'middle',...
    'BackgroundColor', [0.99,0.99,0.99],...
    'HorizontalAlignment', 'left');

ce=sprintf('%4.0f',HotBirdProp.cs.s(HotBirdProp.cn).Nlfu);
text(0.40, 0.85-0.04*HotBirdProp.cs.s(HotBirdProp.cn).nr_fue-0.10, ce,...
    'Color', 'black',...
    'FontSize', 11,...
    'FontUnits', 'normalized',...
    'FontWeight', 'bold',...
    'VerticalAlignment', 'middle',...
    'BackgroundColor', [0.99,0.99,0.99],...
    'HorizontalAlignment', 'left');
end


function rods_data(~,~,hfig)

HotBirdProp=get(hfig,'userdata');
axes(HotBirdProp.handles.data);
cla;
HotBirdProp.cs.calc_rod();

ce=sprintf('Number of rods');
text(0.05, 0.95, ce,...
    'Color', 'black',...
    'FontSize', 11,...
    'FontUnits', 'normalized',...
    'FontWeight', 'bold',...
    'VerticalAlignment', 'middle',...
    'BackgroundColor', [0.99,0.99,0.99],...
    'HorizontalAlignment', 'left');
ce=sprintf('Number');
text(0.05, 0.85, ce,...
    'Color', 'black',...
    'FontSize', 11,...
    'FontUnits', 'normalized',...
    'FontWeight', 'bold',...
    'VerticalAlignment', 'middle',...
    'BackgroundColor', [0.99,0.99,0.99],...
    'HorizontalAlignment', 'left');
ce=sprintf('U235');
text(0.30, 0.85, ce,...
    'Color', 'black',...
    'FontSize', 11,...
    'FontUnits', 'normalized',...
    'FontWeight', 'bold',...
    'VerticalAlignment', 'middle',...
    'BackgroundColor', [0.99,0.99,0.99],...
    'HorizontalAlignment', 'left');
ce=sprintf('BA');
text(0.55, 0.85, ce,...
    'Color', 'black',...
    'FontSize', 11,...
    'FontUnits', 'normalized',...
    'FontWeight', 'bold',...
    'VerticalAlignment', 'middle',...
    'BackgroundColor', [0.99,0.99,0.99],...
    'HorizontalAlignment', 'left');

for k=1:HotBirdProp.cs.nr_rod
    ce=sprintf('%4.0f',HotBirdProp.cs.nr_rod2(k));
    text(0.05, 0.85-0.04*k, ce,...
        'Color', 'black',...
        'FontSize', 11,...
        'FontUnits', 'normalized',...
        'FontWeight', 'bold',...
        'VerticalAlignment', 'middle',...
        'BackgroundColor', [0.99,0.99,0.99],...
        'HorizontalAlignment', 'left');
end

for k=1:HotBirdProp.cs.nr_rod
    ce=sprintf('%5.2f',HotBirdProp.cs.rodenr2(k));
    text(0.30, 0.85-0.04*k, ce,...
        'Color', 'black',...
        'FontSize', 11,...
        'FontUnits', 'normalized',...
        'FontWeight', 'bold',...
        'VerticalAlignment', 'middle',...
        'BackgroundColor', [0.99,0.99,0.99],...
        'HorizontalAlignment', 'left');
end

for k=1:HotBirdProp.cs.nr_rod
    ce=sprintf('%5.2f',HotBirdProp.cs.rodba2(k));
    if(HotBirdProp.cs.rodba2(k))
        text(0.55, 0.85-0.04*k, ce,...
            'Color', 'black',...
            'FontSize', 11,...
            'FontUnits', 'normalized',...
            'FontWeight', 'bold',...
            'VerticalAlignment', 'middle',...
            'BackgroundColor', [0.99,0.99,0.99],...
            'HorizontalAlignment', 'left');
    end
end

ce=sprintf('Total Number');
text(0.05, 0.85-0.04*HotBirdProp.cs.nr_rod-0.10, ce,...
    'Color', 'black',...
    'FontSize', 11,...
    'FontUnits', 'normalized',...
    'FontWeight', 'bold',...
    'VerticalAlignment', 'middle',...
    'BackgroundColor', [0.99,0.99,0.99],...
    'HorizontalAlignment', 'left');

ce=sprintf('%4.0f',HotBirdProp.cs.Nrods);
text(0.40, 0.85-0.04*HotBirdProp.cs.nr_rod-0.10, ce,...
    'Color', 'black',...
    'FontSize', 11,...
    'FontUnits', 'normalized',...
    'FontWeight', 'bold',...
    'VerticalAlignment', 'middle',...
    'BackgroundColor', [0.99,0.99,0.99],...
    'HorizontalAlignment', 'left');
end


function write_btf_file(~,~,hfig)

HotBirdProp=get(hfig,'userdata');

HotBirdProp.cs.writebtffile;

end

