function y=eq_Energy_core(alfa,tl,Wg,Wl,qprimw,q3l,tsat,P,A,hz,chflow,tlp)
kmax=size(alfa,1);
y=zeros(size(alfa));
ett=ones(size(alfa(1,:)));
k=2:kmax;

y(k,:)=eq_E(Wl(k,:),Wg(k,:),tl(k,:),P,tsat)-...
    eq_E(Wl(k-1,:),Wg(k-1,:),tl(k-1,:),P,tsat)-...
    (qprimw(k,:)+ q3l(k,:).*(1-alfa(k,:)).*A(k,:))*hz/100;
y(1,:)=eq_E(Wl(1,:),Wg(1,:),tl(1,:),P,tsat)-...
       eq_E(chflow,0*ett,tlp*ett,P,tsat)-...
       (qprimw(1,:)+ q3l(1,:).*(1-alfa(1,:)).*A(1,:))*hz/100;
y=y/1e5; % Scaling for numerical purposes