function hfig=setupwin()

hpar=gcf;

refufile=get(findobj(hpar,'Tag','RefufileEdit'), 'String');

% Setup figure
fh=500;
fw=310;
hfig = figure('Color',[0.8 0.8 0.8], ...
    'Name','Refueling settings',...
	'FileName','/cm/tools/source/mlab/cm_distplot/private/setupwin.m', ...
	'Position',[400 400 fw fh], ...
	'Tag','Refusetupwin', ...
    'Resize','off',...
    'MenuBar','none',...
	'ToolBar','none',...
    'WindowStyle','modal');

refu=openrefu(refufile,hfig);

% Polca command
uicontrol('Parent',hfig, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[15 440 80 20], ...
	'String','Polca cmd:', ...
	'Style','text');
uicontrol('Parent',hfig, ...
	'BackgroundColor',[1 1 1], ...
	'Position',[120 440 170 22], ...
	'String',refu.polcacmd, ...
	'Style','edit', ...
	'Tag','PolcaCmdEdit',...
    'Enable','off');
    
% Skyffel command
uicontrol('Parent',hfig, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[15 410 80 20], ...
	'String','Skyffel cmd:', ...
	'Style','text');
uicontrol('Parent',hfig, ...
	'BackgroundColor',[1 1 1], ...
	'Position',[120 410 170 22], ...
	'String',refu.skyffelcmd, ...
	'Style','edit', ...
	'Tag','SkyffelCmdEdit',...
    'Enable','off');  

% Skyinp-file
uicontrol('Parent',hfig, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[15 380 80 20], ...
	'String','Skyinp-file:', ...
	'Style','text');
uicontrol('Parent',hfig, ...
	'BackgroundColor',[1 1 1], ...
	'Position',[120 380 170 22], ...
    'String',refu.skyinpfile,...
	'Style','edit', ...
	'Tag','SkyinpfileEdit',...
    'Enable','off');

% Compkhot-file
uicontrol('Parent',hfig, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[15 350 80 20], ...
	'String','Comp-file:', ...
	'Style','text');
uicontrol('Parent',hfig, ...
	'BackgroundColor',[1 1 1], ...
	'Position',[120 350 170 22], ...
    'String',refu.compkhotfile,...
	'Style','edit', ...
	'Tag','CompkhotfileEdit',...
    'Enable','off');

% Crtyp-file
uicontrol('Parent',hfig, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[15 320 80 20], ...
	'String','Crtyp-file:', ...
	'Style','text');
uicontrol('Parent',hfig, ...
	'BackgroundColor',[1 1 1], ...
	'Position',[120 320 170 22], ...
    'String',refu.crtypfile,...
	'Style','edit', ...
	'Tag','CrtypfileEdit',...
    'Enable','off');

% Pool-file
uicontrol('Parent',hfig, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[15 290 80 20], ...
	'String','Poolfile:', ...
	'Style','text');
uicontrol('Parent',hfig, ...
	'BackgroundColor',[1 1 1], ...
	'Position',[120 290 170 22], ...
	'Style','edit', ...
    'String',refu.poolfile,...
	'Tag','PoolfileEdit',...
    'Enable','off');

% Option-file
uicontrol('Parent',hfig, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[15 260 80 20], ...
	'String','Option-file:', ...
	'Style','text');
uicontrol('Parent',hfig, ...
	'BackgroundColor',[1 1 1], ...
	'Position',[120 260 170 22], ...
	'Style','edit', ...
    'String',refu.optionfile,...
	'Tag','OptionfileEdit',...
    'Enable','off');

% BOC-file
uicontrol('Parent',hfig, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[15 230 80 20], ...
	'String','BOC-file:', ...
	'Style','text');
uicontrol('Parent',hfig, ...
	'BackgroundColor',[1 1 1], ...
	'Position',[120 230 170 22], ...
	'String',refu.bocfile, ...
	'Style','edit', ...
	'Tag','BocfileEdit',...
    'Enable','off');

% EOC-file
uicontrol('Parent',hfig, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[15 200 80 20], ...
	'String','EOC-file:', ...
	'Style','text');
uicontrol('Parent',hfig, ...
	'BackgroundColor',[1 1 1], ...
	'Position',[120 200 170 22], ...
	'String',refu.eocfile, ...
	'Style','edit', ...
	'Tag','EocfileEdit',...
    'Enable','off');

% ASYID-file
uicontrol('Parent',hfig, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[15 170 80 20], ...
	'String','ASYID-file:', ...
	'Style','text');
uicontrol('Parent',hfig, ...
	'BackgroundColor',[1 1 1], ...
	'Position',[120 170 170 22], ...
	'String',refu.asyidfile, ...
	'Style','edit', ...
	'Tag','AsyidfileEdit',...
    'Enable','off');

% ASYWEI-file
uicontrol('Parent',hfig, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[15 140 80 20], ...
	'String','ASYWEI-file:', ...
	'Style','text');
uicontrol('Parent',hfig, ...
	'BackgroundColor',[1 1 1], ...
	'Position',[120 140 170 22], ...
	'String',refu.asyweifile, ...
	'Style','edit', ...
	'Tag','AsyweifileEdit',...
    'Enable','off');

% ASYTYP-file
uicontrol('Parent',hfig, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[15 110 80 20], ...
	'String','ASYTYP-file:', ...
	'Style','text');
uicontrol('Parent',hfig, ...
	'BackgroundColor',[1 1 1], ...
	'Position',[120 110 170 22], ...
	'String',refu.asytypfile, ...
	'Style','edit', ...
	'Tag','AsytypfileEdit',...
    'Enable','off');

% Symmetry
uicontrol('Parent',hfig, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[15 80 80 20], ...
	'String','Symmetry:', ...
	'Style','text');
uicontrol('Parent',hfig, ...
	'BackgroundColor',[1 1 1], ...
	'Position',[120 80 170 22], ...
	'String',refu.symmetry, ...
	'Style','edit', ...
	'Tag','SymmetryEdit',...
    'Enable','off');


% Buttons
uicontrol('Parent',hfig, ...
	'Callback',{@refusetup_save,refufile,refu}, ...
	'Position',[70 20 100 30], ...
	'String','Ok', ...
	'Tag','SaveButton',...
    'Enable','off');

uicontrol('Parent',hfig, ...
	'Callback',@refusetup_cancel, ...
	'Position',[190 20 100 30], ...
	'String','Cancel', ...
	'Tag','CancelButton');


if ~isempty(refu)
    set(findobj(hfig,'Tag','SkyinpfileEdit'), 'Enable', 'on');
    set(findobj(hfig,'Tag','CompkhotfileEdit'), 'Enable', 'on');
    set(findobj(hfig,'Tag','CrtypfileEdit'), 'Enable', 'on');
    set(findobj(hfig,'Tag','OptionfileEdit'), 'Enable', 'on');
    set(findobj(hfig,'Tag','PoolfileEdit'), 'Enable', 'on');
    set(findobj(hfig,'Tag','BocfileEdit'), 'Enable', 'on');
    set(findobj(hfig,'Tag','EocfileEdit'), 'Enable', 'on');
    set(findobj(hfig,'Tag','AsyidfileEdit'), 'Enable', 'on');
    set(findobj(hfig,'Tag','AsyweifileEdit'), 'Enable', 'on');
    set(findobj(hfig,'Tag','AsytypfileEdit'), 'Enable', 'on');
    set(findobj(hfig,'Tag','SymmetryEdit'), 'Enable', 'on');
    set(findobj(hfig,'Tag','SaveButton'), 'Enable', 'on');
    set(findobj(hfig,'Tag','PolcaCmdEdit'), 'Enable', 'on');
    set(findobj(hfig,'Tag','SkyffelCmdEdit'), 'Enable', 'on');
end

end


function refu=openrefu(refufile,hfig)

if exist(refufile,'file')
    refu=load(refufile);
else
    a=questdlg('No refufile found, create new?','','Yes','No','Yes');
    switch a
        case 'Yes'
            refu=refudefault();
        case 'No'
            refu=[];
            return;
    end
end

end


function refusetup_save(hObject,eventdata,refufile,refu)

refu.skyinpfile=get(findobj(get(hObject,'Parent'),'Tag','SkyinpfileEdit'), 'String');
refu.compkhotfile=get(findobj(get(hObject,'Parent'),'Tag','CompkhotfileEdit'), 'String');
refu.crtypfile=get(findobj(get(hObject,'Parent'),'Tag','CrtypfileEdit'), 'String');
refu.poolfile=get(findobj(get(hObject,'Parent'),'Tag','PoolfileEdit'), 'String');
refu.optionfile=get(findobj(get(hObject,'Parent'),'Tag','OptionfileEdit'), 'String');
refu.bocfile=get(findobj(get(hObject,'Parent'),'Tag','BocfileEdit'), 'String');
refu.eocfile=get(findobj(get(hObject,'Parent'),'Tag','EocfileEdit'), 'String');
refu.asyidfile=get(findobj(get(hObject,'Parent'),'Tag','AsyidfileEdit'), 'String');
refu.asyweifile=get(findobj(get(hObject,'Parent'),'Tag','AsyweifileEdit'), 'String');
refu.asytypfile=get(findobj(get(hObject,'Parent'),'Tag','AsytypfileEdit'), 'String');
refu.symmetry=str2num(get(findobj(get(hObject,'Parent'),'Tag','SymmetryEdit'), 'String'));
refu.polcacmd=get(findobj(get(hObject,'Parent'),'Tag','PolcaCmdEdit'), 'String');
refu.skyffelcmd=get(findobj(get(hObject,'Parent'),'Tag','SkyffelCmdEdit'), 'String');

if exist(refufile,'file')
    save(refufile,'-append','-struct','refu');
else
    save(refufile,'-struct','refu');
end

close(gcf)
end


function refusetup_cancel(hObject,eventdata)
    close(gcf); 
end


function refu=refudefault()
    refu.skyinpfile='refu/sky-inp.txt';
    refu.compkhotfile='off/comp-khot.txt';
    refu.crtypfile='templ/crtyp.txt';
    refu.poolfile='';
    refu.optionfile='';
    refu.bocfile='dist/boc.dat';
    refu.eocfile='dist/eoc.dat';
    refu.asyidfile='refu/asyid.txt';
    refu.asyweifile='refu/asywei.txt';
    refu.asytypfile='pol/asytyp.txt';
    refu.symmetry=3;
    
    refu.polcacmd='polca';
    refu.skyffelcmd='skyffel';
    
    refu.freshfuel=[];
    
    refu.freshload=[];
    refu.poolload=[];
    refu.shuffles=[];
end
