%@(#)   shuffle.m 1.1	 05/07/13     10:29:41
%
%
%function [lto,lbuid]=shuffle(curfile,bocfile,OK,maxop,prifil,curpos)
function [lto,lbuid]=shuffle(curfile,bocfile,OK,maxop,prifil,curpos)
if nargin<4, maxop=1000;end
if nargin<5, prifil='infil.lis';end
if nargin<6 curpos=[16 16];end
if isstr(prifil),
  fid=fopen(prifil,'w');
  clo=1;
elseif prifil~=0
  fid=prifil;
  clo=0;
else
  disp('error in function shuffle, argument fil must not be = 0');
end;
[buid,mminj,konrod,bb,hy,mz,ks,buntyp]=readdist7(curfile,'asyid');
kkan=mz(14);
if nargin<3, OK=ones(kkan,1);end
crid=readdist7(curfile,'crid');
buidboc=readdist7(bocfile,'asyid');
burnup=readdist7(curfile,'burnup');	%ska ändras
%kinf=kinf2mlab(curfile);
vhist=readdist7(curfile,'vhist');	%ska ändras
sshist=readdist7(curfile,'sshist');	%ska ändras
buntyp=readdist7(curfile,'asytyp');
kkan=mz(14);
ican=fastcatch('dummy',crid);
konrod=zeros(mz(69),1);
konrod(ican)=ones(size(ican));
ikan=filtcr(konrod,mminj,0.5,1.5);
if length(ikan)>0,
  ikan1=[ikan(:,1);ikan(:,2);ikan(:,3);ikan(:,4)];
  OK(ikan1)=zeros(length(ikan1),1);
end
[from,to,ready,fuel]=initvec(buid,buidboc,OK);
idum=find(fuel==0);idum=idum(1);
burndum=burnup(:,idum);			%ändra
vhidum=vhist(:,idum);			%ändra
sshidum=sshist(:,idum);			%ändra
bundum=buntyp(idum,:);
%kinfdum=kinf(idum);
iok=find(OK==1);
conv=0;
fprintf(fid,'%s\n','TEXT GENERATED BY MATLAB');
for i1=1:maxop,
  [ifrom,ito]=findmove(curpos,OK,from,to,fuel,mminj);
  ifrom=ifrom(1);ito=ito(1);
  if max(ifrom)==0, conv=-1;break;end
  [ik,jk]=find(ikan==ito);
  lto(i1)=ito;
  lbuid(i1,:)=buid(ifrom,:);
  if length(ik)>0,
    l=find((1:4)~=jk);
    if max(fuel(ikan(ik,l)))==0,
      disp('Obs!!! Forsta patron i supercell');
      printsfg(0,lfrom(i),lto(i),'dummy',mminj,1);
      printsfg(fid,lfrom(i),lto(i),'dummy',mminj,1);
    end;
  end
  printsfg(fid,ifrom,ito,buid(ifrom,:),mminj);
  printsfg(0,ifrom,ito,buid(ifrom,:),mminj);
  [ik,jk]=find(ikan==ifrom);
  if length(ik)>0,
    l=find((1:4)~=jk);
    if max(fuel(ikan(ik,l)))==0,
      disp('Varning!!! Supercell tom');
      printsfg(0,ifrom,ito,'dummy',mminj,2);
      printsfg(fid,ifrom,ito,'dummy',mminj,2);
    end;  
  end
  curpos=knum2cpos(ifrom,mminj);
  fuel(ifrom)=0;
  fuel(ito)=1;
  ready(ito)=1;
  burnup(:,ito)=burnup(:,ifrom);	%ändra
  buid(ito,:)=buid(ifrom,:);
  buid(ifrom,:)='dummy ';
  if all(ready(iok)==1), conv=1;break;end
end  
fprintf(fid,'%s\n','END');
fclose(fid);
if conv==-1,
  disp('Shuffling no longer possible in defined area');
elseif conv==0,
  disp('Maximum number of operations given by  user reached');
elseif conv==1,
  disp('All shuffling in defined area completed');  
end
ierr=0;
ierr=writedist7(curfile,'asyid',buid);
if ierr>0, disp(['error when writing asyid to ',curfile]);end		%ändra och kolla
ierr=writedist7(curfile,'asyryp',buntyp);
if ierr>0, disp(['error when writing asytyp to ',curfile]);end
ierr=writedist7(curfile,'BURNUP',burnup);
if ierr>0, disp(['error when writing burnup to ',curfile]);end
ierr=writedist7(curfile,'SSHIST',sshist);
if ierr>0, disp(['error when writing sshist to ',curfile]);end
ierr=writedist7(curfile,'VHIST',vhist);
if ierr>0, disp(['error when writing vhist to ',curfile]);end
end
