function fig = cyplot7()
hpar=gcf;
defdist=setprop(4);
load sim/simfile
[d,mminj,konrod,bb,hy,mz,ks,asytyp,asyref,distlist,...
 staton,masfil,rubrik,detpos,fu,op,au,flopos,soufil]=readdist7(filenames(1,:));
distlist=[distlist;'SDM     ';'SDM3D   '];
frad=bb(104);
keff=bb(96);
void=100*hy(134);
[efph,mminj,konrod,bb]=readdist7(bocfile,'efph');
burnup=bb(46);
cydist=['BURNUP  ';'POWER   ';'SDM     ';'THMARG  ';...
        'LHGR    ';'LHGR_PEL';'APLHGR  ';'SHF     ';...
        'FL_LHGR1';'FL_LHGR2';'FL_LHGR3';'FL_APLHG';...
        'FL_SHF  ';'CPR     ';'FL_CPR  ';'SDM3D   ';...
        'VOID    ';'CHFLOW  ';'FLWORI  ';'KHOT    ';];
i=mbucatch(distlist,cydist);
i=find(i);
distlist=ascsort(distlist(i,:));

h0 = figure('Color',[0.8 0.8 0.8], ...
	'FileName','/cm/tools/source/mlab/cm_distplot/cyplot7.m', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[580 212 373 404], ...
	'Tag','Fig3', ...
	'ToolBar','none');
i=strmatch(defdist,distlist);if isempty(i),i=1;end
hval(1) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[22.4 20 100 278.4], ...
	'String',distlist, ...
	'Style','listbox', ...
	'Tag','Listbox1', ...
	'Value',i);
hval(2) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[160 280 119.2 19.2], ...
	'String',sprintf('Frad:%10.2f',frad), ...
	'Style','text', ...
	'Tag','StaticText1');
hval(3) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[160.8 246.4 116.8 20], ...
	'String',sprintf('keff:%10.5f',keff), ...
	'Style','text', ...
	'Tag','StaticText2');
hval(4) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[160 212.8 116.8 18.4], ...
	'String',sprintf('Void:%10.2f',void), ...
	'Style','text', ...
	'Tag','StaticText3');
hval(5) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[160.8 181.6 117.6 20], ...
	'String',sprintf('Burnup:%10.2f',burnup), ...
	'Style','text', ...
	'Tag','StaticText4');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[160 132 54.4 30.4], ...
	'String','env MIN', ...
	'Callback','cyenv7(''min'')', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[228.8 132 53.6 30.4], ...
	'String','env MAX', ...
	'Callback','cyenv7(''max'')', ...
	'Tag','Pushbutton2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[180.8 92 78.4 27.2], ...
	'String','Plot', ...
	'Callback','cyed7(9)', ...
	'Tag','Pushbutton3');
hval(7) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[160 20.8 119.2 19.2], ...
	'Style','slider', ...
	'Callback','cyed7(7)', ...
	'Tag','Slider1');
hval(6) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[192.8 45.6 53.6 21.6], ...
	'String',num2str(blist(1)), ...
	'Style','edit', ...
	'Callback','cyed7(6)', ...
	'Tag','EditText1');
if nargout > 0, fig = h0; end
set(gcf,'userdata',[hval hpar]);
