function preplot7()

load sim/simfile

g=[];
w=[];
i=find(conrod(1,:)==',');
j=find(conrod(1,:)=='=');
i=[0 i length(conrod(1,:))+1];
for ii=1:length(j)
  g=[g str2num(conrod(1,i(ii)+1:j(ii)-1))];
  w=[w str2num(conrod(1,j(ii)+1:i(ii+1)-1))];
end
h0 = figure('Color',[0.8 0.8 0.8], ...
	'FileName','/cm/tools/matlab/cm_distplot/preplot7.m', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[600 444 560 420], ...
	'Tag','Fig1', ...
	'ToolBar','none');
hval(22) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[155 143 25 145], ...
	'Style','slider', ...
	'Callback','preed7(22)', ...
	'Tag','Slider1');
	if length(w)>0,set(hval(22),'Value',1-w(1)/100);end
hval(23) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[190 143 25 145], ...
	'Style','slider', ...
	'Callback','preed7(23)', ...
	'Tag','Slider2');
	if length(w)>1,set(hval(23),'Value',1-w(2)/100);end
hval(24) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[225 143 25 145], ...
	'Style','slider', ...
	'Callback','preed7(24)', ...
	'Tag','Slider3');
	if length(w)>2,set(hval(24),'Value',1-w(3)/100);end
hval(25) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[260 143 25 145], ...
	'Style','slider', ...
	'Callback','preed7(25)', ...
	'Tag','Slider4');
	if length(w)>3,set(hval(25),'Value',1-w(4)/100);end
hval(26) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[295 143 25 145], ...
	'Style','slider', ...
	'Callback','preed7(26)', ...
	'Tag','Slider5');
	if length(w)>4,set(hval(26),'Value',1-w(5)/100);end
hval(27) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[330 143 25 145], ...
	'Style','slider', ...
	'Callback','preed7(27)', ...
	'Tag','Slider6');
	if length(w)>5,set(hval(27),'Value',1-w(6)/100);end
hval(28) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[365 143 25 145], ...
	'Style','slider', ...
	'Callback','preed7(28)', ...
	'Tag','Slider7');
	if length(w)>6,set(hval(28),'Value',1-w(7)/100);end
hval(29) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[400 143 25 145], ...
	'Style','slider', ...
	'Callback','preed7(29)', ...
	'Tag','Slider8');
	if length(w)>7,set(hval(29),'Value',1-w(8)/100);end
hval(30) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[225 20 200 18], ...
	'Style','slider', ...
	'Callback','preed7(30)', ...
	'Tag','Slider9');
hval(21) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[325 50 100 18], ...
	'String',num2str(blist(1)), ...
	'Style','edit', ...
	'Callback','preed7(21,''efph'')', ...
	'Tag','EditText1');
hval(1) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[155 300 25 20], ...
	'Style','edit', ...
	'Callback','preed7(1)', ...
	'Tag','EditText3');
	if length(g)>0,set(hval(1),'String',num2str(g(1)));end
hval(2) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[190 300 25 20], ...
	'Style','edit', ...
	'Callback','preed7(2)', ...
	'Tag','EditText4');
	if length(g)>1,set(hval(2),'String',num2str(g(2)));end
hval(3) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[225 300 25 20], ...
	'Style','edit', ...
	'Callback','preed7(3)', ...
	'Tag','EditText5');
	if length(g)>2,set(hval(3),'String',num2str(g(3)));end
hval(4) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[260 300 25 20], ...
	'Style','edit', ...
	'Callback','preed7(4)', ...
	'Tag','EditText6');
	if length(g)>3,set(hval(4),'String',num2str(g(4)));end
hval(5) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[295 300 25 20], ...
	'Style','edit', ...
	'Callback','preed7(5)', ...
	'Tag','EditText7');
	if length(g)>4,set(hval(5),'String',num2str(g(5)));end
hval(6) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[330 300 25 20], ...
	'Style','edit', ...
	'Callback','preed7(6)', ...
	'Tag','EditText8');
	if length(g)>5,set(hval(6),'String',num2str(g(6)));end
hval(7) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[365 300 25 20], ...
	'Style','edit', ...
	'Callback','preed7(7)', ...
	'Tag','EditText9');
	if length(g)>6,set(hval(7),'String',num2str(g(7)));end
hval(8) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[400 300 25 20], ...
	'Style','edit', ...
	'Callback','preed7(8)', ...
	'Tag','EditText10');
	if length(g)>7,set(hval(8),'String',num2str(g(8)));end
hval(9) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[155 113 25 20], ...
	'Style','edit', ...
	'Callback','preed7(9)', ...
	'Tag','EditText2');
	if length(w)>0,set(hval(9),'String',num2str(w(1)));end
hval(10) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[190 113 25 20], ...
	'Style','edit', ...
	'Callback','preed7(10)', ...
	'Tag','EditText11');
	if length(w)>1,set(hval(10),'String',num2str(w(2)));end
hval(11) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[225 113 25 20], ...
	'Style','edit', ...
	'Callback','preed7(11)', ...
	'Tag','EditText12');
	if length(w)>2,set(hval(11),'String',num2str(w(3)));end
hval(12) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[260 113 25 20], ...
	'Style','edit', ...
	'Callback','preed7(12)', ...
	'Tag','EditText13');
	if length(w)>3,set(hval(12),'String',num2str(w(4)));end
hval(13) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[295 113 25 20], ...
	'Style','edit', ...
	'Callback','preed7(13)', ...
	'Tag','EditText14');
	if length(w)>4,set(hval(13),'String',num2str(w(5)));end
hval(14) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[330 113 25 20], ...
	'Style','edit', ...
	'Callback','preed7(14)', ...
	'Tag','EditText15');
	if length(w)>5,set(hval(14),'String',num2str(w(6)));end
hval(15) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[365 113 25 20], ...
	'Style','edit', ...
	'Callback','preed7(15)', ...
	'Tag','EditText16');
	if length(w)>6,set(hval(15),'String',num2str(w(7)));end
hval(16) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[400 113 25 20], ...
	'Style','edit', ...
	'Callback','preed7(16)', ...
	'Tag','EditText17');
	if length(w)>7,set(hval(16),'String',num2str(w(8)));end
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[15 295 60 28], ...
	'String','Cycle step', ...
	'Callback','cycstep7', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[85 295 60 28], ...
	'String','Power step', ...
	'Callback','powstep7(''fg'')', ...
	'Tag','Pushbutton2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[15 255 60 28], ...
	'String','Burnup step', ...
	'Callback','burstep7;prestep7(''fwd'')', ...
	'Tag','Pushbutton3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[85 255 60 28], ...
	'String','Sdm step', ...
	'Callback','sdmstep7', ...
	'Tag','Pushbutton4');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[15 215 60 28], ...
	'String','Cycle sdm', ...
	'Callback','cycsdm7', ...
	'Tag','Pushbutton5');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[85 215 60 28], ...
	'String','Copy prev', ...
	'Callback','copcon7', ...
	'Tag','Pushbutton6');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[15 175 60 28], ...
	'String','Auto k', ...
	'Callback','autok7', ...
	'Tag','Pushbutton7');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[85 175 60 28], ...
	'String','Auto seq', ...
	'Callback','autoseq7', ...
	'Tag','Pushbutton8');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[15 135 60 28], ...
	'String','Matstab', ...
	'Callback','stabstep7', ...
	'Tag','Pushbutton9');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[15 80 80 18], ...
	'String','Power:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[15 50 80 18], ...
	'String','HC-flow:', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[15 20 80 18], ...
	'String','Tlowp:', ...
	'Style','text', ...
	'Tag','StaticText3');
hval(17) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[110 80 80 18], ...
	'String',pow(1,:), ...
	'Style','edit', ...
	'Callback','preed7(17,''pow'')', ...
	'Tag','EditText18');
hval(18) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[110 50 80 18], ...
	'String',hc(1,:), ...
	'Style','edit', ...
	'Callback','preed7(18,''hc'')', ...
	'Tag','EditText19');
hval(19) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[110 20 80 18], ...
	'String',tlowp(1,:), ...
	'Style','edit', ...
	'Callback','preed7(19,''tlowp'')', ...
	'Tag','EditText20');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[225 80 85 18], ...
	'String','MANGRP-file:', ...
	'Style','text', ...
	'Tag','StaticText4');
hval(20) = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[325 80 100 18], ...
	'String',mangrpfile, ...
	'Style','edit', ...
	'Callback','preed7(20,''mangrpfile'')', ...
	'Tag','EditText21');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[225 50 85 18], ...
	'String','Step:', ...
	'Style','text', ...
	'Tag','StaticText5');
if nargout > 0, fig = h0; end
set(gcf,'userdata',hval);
