function varargout = write_cmsplot_readme(ver)

% Programmers note: if you change this readme file, please change the date
% in variable versionread so it is updated.

versionread = 'Readme_cmsplot_save Version 2012-02-17';
if nargin == 1
    varargout{1} = versionread;
    return
end

fid = fopen('Readme_cmsplot_save.txt','w+');
Readmetext = '\n \n This file is automatically generated when saving data with cmsplot. \n \nThe matfile will contain the data as they are stored in matlab (cells or matrices) \n \n  The excel files will present the data in columns if the amount of data is below 256 columns \nelse it will stor data in rows.The file will contain a matrix if the data is on uniform nod format and then only the data will be \npresented, if the data is in subnode format the axial height will be presented \n in the column (or row) next to the data. In case of maps the axis will be presented the same as in cmsplot, \n and with single assembly data the channel number will be presented. \n \n The ascii file will be presented in the same way as the excel file with two exceptions, \n the data will always be stored in columns and the axis for maps will be saved as row at the begining \n first x-axis and the y-axis';
fprintf(fid,versionread);
fprintf(fid,Readmetext);
fclose(fid);

