%%
Ts=0.04;
Fs=1/Ts;
[P,f]=spectrum(x,2048,[],[],Fs);
Hburg=spectrum.burg(30);
pburg=psd(Hburg,x,'Fs',Fs);
%%
Hcov=spectrum.cov(30);
pcov=psd(Hcov,x,'Fs',Fs);
Hmcov=spectrum.mcov;
pmcov=psd(Hmcov,x,'Fs',Fs);
Hmtm=spectrum.mtm;
Pmt=psd(Hmtm,x,'Fs',Fs);
Hper=spectrum.periodogram('Hann');
pper=psd(Hper,x,'Fs',Fs);
Hwel=spectrum.welch('hann',4096);
pwel=psd(Hwel,x,'Fs',Fs);
Hyul=spectrum.yulear(30);
pyul=psd(Hyul,x,'Fs',Fs);
%%
figure
loglog(f,P(:,1));
hold all
%%
loglog(pburg.Frequencies,abs(pburg.Data))
loglog(pcov.Frequencies,abs(pcov.Data))
loglog(pmcov.Frequencies,abs(pmcov.Data))
loglog(Pmt.Frequencies,abs(Pmt.Data))
loglog(pper.Frequencies,abs(pper.Data))
loglog(pwel.Frequencies,abs(pwel.Data))
loglog(pyul.Frequencies,abs(pyul.Data))
legend('Classic','Burg','Cov','Mcov','Mtm','Per','Wel','Yul');shg