function choise=asyidchoise(pool);
hpar=gcf;
ai=pool(:,8:23);
bu=pool(:,1:7);
ty=pool(:,24:27);
kh=pool(:,28:34);
sp=setstr(32*ones(size(pool,1),1));
h0 = figure('Color',[0.8 0.8 0.8], ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[658 36 330 546], ...
	'ToolBar','none');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[30 120 225 310], ...
	'String',[ai ty sp bu sp sp kh], ...
	'FontName','courier', ...
	'FontSize',8, ...
	'Style','listbox', ...
	'Tag','Listbox1', ...
	'Value',1);
hOK = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[33 55 75 30], ...
	'String','OK', ...
	'Tag','Pushbutton1');
hCa = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[160 55 75 30], ...
	'String','Cancel', ...
	'Tag','Pushbutton2');
choise=[];
knapp=0;
while knapp==0
	waitforbuttonpress;
	pause(.1);
	hobj = get(h0,'currentobject');
	s = get(hobj,'Tag');
	if isempty(s),s='nochoise';end
	switch s
	case 'Pushbutton1'
		v = get(h1,'Value');
		choise = ai(v,:);
		delete(h0);
		knapp=1;
	case 'Pushbutton2'
		delete(h0);
		knapp=1;
	end
end
