%function refuwin7
function refuwin7
hpar=gcf;
h(1) = figure('Color',[0.8 0.8 0.8], ...
	'FileName','/cm/tools/source/mlab/cm_distplot/refuwin7.m', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[523 477 396 411], ...
	'Tag','Fig1', ...
	'ToolBar','none');
h1 = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[15 275 80 20], ...
	'String','Poolfile:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[15 245 80 20], ...
	'String','Option-file:', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[15 215 80 20], ...
	'String','EOC-file:', ...
	'Style','text', ...
	'Tag','StaticText3');
h1 = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[15 185 80 20], ...
	'String','ASYID-file:', ...
	'Style','text', ...
	'Tag','StaticText4');
h1 = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[15 155 80 20], ...
	'String','ASYWEI-file:', ...
	'Style','text', ...
	'Tag','StaticText5');
h1 = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[15 125 80 20], ...
	'String','ASYTYP-file:', ...
	'Style','text', ...
	'Tag','StaticText6');
h(2) = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[100 275 105 22], ...
	'Style','edit', ...
	'Tag','EditText1');
h(3) = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[100 245 105 22], ...
	'Style','edit', ...
	'Tag','EditText2');
h(4) = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[100 215 105 22], ...
	'String','dist/eoc.dat', ...
	'Style','edit', ...
	'Tag','EditText3');
h(5) = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[100 185 105 22], ...
	'String','refu/asyid.txt', ...
	'Style','edit', ...
	'Tag','EditText4');
h(6) = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[100 155 105 22], ...
	'String','refu/asywei.txt', ...
	'Style','edit', ...
	'Tag','EditText5');
h(7) = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[100 125 105 22], ...
	'String','pol/asytyp.txt', ...
	'Style','edit', ...
	'Tag','EditText6');
h(13) = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'Callback','ldfresh7(100)', ...
	'ListboxTop',0, ...
	'Position',[220 275 80 22], ...
	'String','Ld 100 fresh', ...
	'Tag','Pushbutton1');
h(15) = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'Callback','ldfresh7(10)', ...
	'ListboxTop',0, ...
	'Position',[220 245 80 22], ...
	'String','Ld 10 fresh', ...
	'Tag','Pushbutton2');
h(16) = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','ldfresh7(2)', ...
	'ListboxTop',0, ...
	'Position',[220 215 80 22], ...
	'String','Ld 2 fresh', ...
	'Tag','Pushbutton3');
h1 = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'Callback','lowper7', ...
	'ListboxTop',0, ...
	'Position',[220 185 80 22], ...
	'String','Move in fresh', ...
	'Tag','Pushbutton4');
h(14) = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'Callback','refumov7', ...
	'ListboxTop',0, ...
	'Position',[220 155 80 22], ...
	'String','Move', ...
	'Tag','Pushbutton5');
h1 = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Min',1, ...
	'Position',[220 125 80 22], ...
	'String',['Reins to x';'Reins low ';'Reins rank'], ...
	'Callback','reval', ...
	'Style','popupmenu', ...
	'Tag','PopupMenu1', ...
	'Value',1);
h1 = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[15 95 55 20], ...
	'String','Symmetry:', ...
	'Style','text', ...
	'Tag','StaticText7');
h(8) = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[80 95 35 22], ...
	'String','3', ...
	'Style','edit', ...
	'Tag','EditText7');
h1 = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[180 95 75 20], ...
	'String','Fresh asytyp:', ...
	'Style','text', ...
	'Tag','StaticText8');
h(9) = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[260 95 40 22], ...
	'Style','edit', ...
	'Tag','EditText8');
h(10) = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[7.2 71.2 84 14.4], ...
	'String','Fresh: ---', ...
	'Style','text', ...
	'Tag','StaticText9');
h(11) = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[108 70 90 16], ...
	'String','Moved: ---', ...
	'Style','text', ...
	'Tag','StaticText10');
h(12) = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[210 70 88 16], ...
	'String','Reinserted: ---', ...
	'Style','text', ...
	'Tag','StaticText11');
h1 = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','refundo7', ...
	'ListboxTop',0, ...
	'Position',[50 25 100 30], ...
	'String','Undo', ...
	'Tag','Pushbutton7');
h1 = uicontrol('Parent',h(1), ...
	'Units','points', ...
	'Callback','refupd7', ...
	'ListboxTop',0, ...
	'Position',[170 25 100 30], ...
	'String','Update', ...
	'Tag','Pushbutton8');
set(h(1),'userdata',[h hpar]);
