%function refuwin
function refuwin
hpar=gcf;


% Setup figure
fh=750;
fw=400;
hfig = figure('Color',[0.8 0.8 0.8], ...
    'Name','Refueling',...
	'FileName','/cm/tools/source/mlab/cm_distplot/refuwin.m', ...
	'Position',[800 200 fw fh], ...
	'Tag','Refuwin', ...
    'Resize','off',...
    'MenuBar','none',...
	'ToolBar','none',...
    'UserData',hpar,...
    'CloseRequestFcn',@closewin);

% Refuel file panel
p1 = uipanel('Parent',hfig,...
    'Title','Refuel file',...
    'Units','Pixels',...
    'Position',[10 fh-70 fw-20 60]);

h1 = uicontrol('Parent',p1, ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[10 10 230 30], ...
    'Callback',@update,...
	'String','refu/refufile.mat', ...
	'Style','edit', ...
	'Tag','RefufileEdit');

h1 = uicontrol('Parent',p1, ...
	'Position',[250 10 30 30], ...
    'Callback',{@setrefufile,hfig},...
	'String','...', ...
	'Style','pushbutton', ...
	'Tag','OpenButton');

h1 = uicontrol('Parent',p1, ...
	'Position',[300 10 70 30], ...
    'Callback',{@setuprefu,hfig},...
	'String','Setup...', ...
	'Style','pushbutton', ...
	'Tag','SetupButton');


% Statistics panel
p2 = uipanel('Parent',hfig,...
    'Title','Statistics',...
    'Units','Pixels',...
    'Position',[10 fh-130 fw-20 50]);

h1 = uicontrol('Parent',p2, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[10 10 110 20], ...
	'String','Fresh: ---', ...
	'Style','text', ...
	'Tag','FreshStat');
h1 = uicontrol('Parent',p2, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[130 10 110 20], ...
	'String','Moved: ---', ...
	'Style','text', ...
	'Tag','MovedStat');
h1 = uicontrol('Parent',p2, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[250 10 110 20], ...
	'String','Reinserted: ---', ...
	'Style','text', ...
	'Tag','ReinsStat');


% Fresh fuel panel
p3 = uipanel('Parent',hfig,...
    'Title','Fresh fuel',...
    'Units','Pixels',...
    'Position',[10 fh-290 fw-20 150]);

h1 = uitable('Parent',p3, ...
	'BackgroundColor',[1 1 1], ...
    'FontName','FixedWidth',...
	'Position',[10 50 fw-40 80], ...
	'Tag','FreshList',...
    'RowName',[],...
    'ColumnName',{'ASYTYP','DESCRIPTION','LOADED','TOTAL'},...
    'ColumnWidth',{50 180 60 50},...
    'CellSelectionCallback',@table_select);

h1 = uicontrol('Parent',p3, ...
	'Callback',{@addfresh,hfig,[]}, ...
    'Enable','off',...
	'Position',[10 10 40 30], ...
	'String','New', ...
	'Tag','AddFreshButton');

h1 = uicontrol('Parent',p3, ...
	'Callback',{@addfresh,hfig,'edit'}, ...
    'Enable','off',...
	'Position',[60 10 40 30], ...
	'String','Edit', ...
	'Tag','EditFreshButton');

h1 = uicontrol('Parent',p3, ...
	'Callback',{@delfresh,hfig}, ...
    'Enable','off',...
	'Position',[110 10 40 30], ...
	'String','Del', ...
	'Tag','DelFreshButton');

h1 = uicontrol('Parent',p3, ...
	'Position',[fw-220 10 40 30], ...
	'String','2', ...
    'Style','edit',...
	'Tag','FreshNumberEdit');

h1 = uicontrol('Parent',p3, ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Min',1, ...
	'Position',[fw-170 5 70 30], ...
	'String',['Low   ';'To x  '], ...
	'Style','popupmenu', ...
	'Tag','LoadFreshModeMenu', ...
	'Value',1);

h1 = uicontrol('Parent',p3, ...
	'Callback',{@loadfresh,hfig}, ...
    'Enable','off',...
	'Position',[fw-90 10 60 30], ...
	'String','Load', ...
	'Tag','LoadFreshButton');


% Fuel pool panel
p4 = uipanel('Parent',hfig,...
    'Title','Fuel pool',...
    'Units','Pixels',...
    'Position',[10 fh-500 fw-20 200]);

h1 = uitable('Parent',p4, ...
	'BackgroundColor',[1 1 1], ...
    'FontName','FixedWidth',...
	'Position',[10 50 fw-40 130],...
	'Tag','PoolList',...
    'RowName',[],...
    'ColumnName',{'ASYID','ASYTYP','KHOT','BURNUP','CRHIST','LASTCYC'},...
    'ColumnWidth',{70 50 60 60 60 40},...
    'CellSelectionCallback',@table_select);

h1 = uicontrol('Parent',p4, ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Min',1, ...
	'Position',[fw-200 5 80 30], ...
	'String',['To x  ';'Low   ';'Rank  '], ...
	'Style','popupmenu', ...
	'Tag','ReinsertModeMenu', ...
	'Value',1);

h1 = uicontrol('Parent',p4, ...
	'Callback',{@reinsert,hfig}, ...
    'Enable','off',...
	'Position',[fw-110 10 80 30], ...
	'String','Reinsert', ...
	'Tag','ReinsertButton');


% Shuffle panel
p5 = uipanel('Parent',hfig,...
    'Title','Shuffles',...
    'Units','Pixels',...
    'Position',[10 fh-680 fw-20 170]);

h1 = uitable('Parent',p5, ...
	'BackgroundColor',[1 1 1], ...
    'FontName','FixedWidth',...
	'Position',[10 50 fw-40 100], ...
	'Tag','ShuffleList', ...
    'RowName',[],...
    'ColumnName',{'FROM','TYP1','KHOT1','TO','TYP2','KHOT2'},...
    'ColumnWidth',{50 60 60 50 60 60},...
    'CellSelectionCallback',@table_select);

h1 = uicontrol('Parent',p5, ...
	'Callback','disp(''Undo callback ...'')', ...
    'Enable','off',...
	'ListboxTop',0, ...
	'Position',[10 10 100 30], ...
	'String','Undo last', ...
	'Tag','UndoButton');

h1 = uicontrol('Parent',p5, ...
	'Callback',{@refumov7,hfig}, ...
    'Enable','off',...
	'Position',[fw-230 10 80 30], ...
	'String','Move', ...
	'Tag','MoveButton');

h1 = uicontrol('Parent',p5, ...
	'Callback','lowper7', ...
    'Enable','off',...
	'Position',[fw-130 10 100 30], ...
	'String','Move in fresh', ...
	'Tag','MoveinFreshButton');


% Buttons
h1 = uicontrol('Parent',hfig, ...
	'Callback',{@update_view,hfig}, ...
    'Enable','on',...
	'Position',[30 20 80 30], ...
	'String','Update', ...
	'Tag','UpdateButton');

h1 = uicontrol('Parent',hfig, ...
	'Callback',{@clearops,hfig}, ...
    'Enable','off',...
	'Position',[190 20 80 30], ...
	'String','Clear', ...
	'Tag','ClearButton');

h1 = uicontrol('Parent',hfig, ...
	'Callback',{@refuel,hfig}, ...
    'Enable','off',...
	'Position',[290 20 80 30], ...
	'String','Apply', ...
	'Tag','RefuelButton');

update(hfig,[]);

end



%% Callbacks

% Open setupwin
function setuprefu(hObject,eventdata,hfig)
h=setupwin;
waitfor(h);
update(hfig,[]);
end


% Set refuel file name
function setrefufile(hObject,eventdata,hfig)
[filename,pathname]=uigetfile('*.mat','Select refufile');
if filename~=0
    refufile=[pathname filename];
    set(findobj(get(hObject,'Parent'),'Tag','RefufileEdit'), 'String',refufile);
end
update(hfig,[]);
end


% Save selection in table user data on event
function table_select(hObject,eventdata)
sel=eventdata.Indices;
set(hObject,'UserData',unique(sel(:,1)));
end


% Load fresh
function loadfresh(hObject, eventdata, hfig)

refufile=get(findobj(hfig,'Tag','RefufileEdit'), 'String');
num=get(findobj(hfig,'Tag','FreshNumberEdit'), 'String');
num=str2num(num);

mode=get(findobj(hfig,'Tag','LoadFreshModeMenu'), 'Value');

ind=get(findobj(hfig,'Tag','FreshList'), 'UserData');
if ~isempty(ind)
    data=get(findobj(hfig,'Tag','FreshList'), 'Data');
    asytyp=data{ind,1};
    
    switch(mode)
        case 1,
            ldfresh7(refufile,asytyp,num);
        case 2,
            hpar=get(hfig,'UserData');
            figure(hpar);
            [x,y]=ginput(num/2);
            pos=[x y];
            ldfreshtox(refufile,asytyp,pos);
    end
    
    update(hfig,[]);
end

end


% Update with new operations
function refuel(hObject,eventdata,hfig)
refufile=get(findobj(hfig,'Tag','RefufileEdit'), 'String');
refupd7(refufile);

update(hfig,[]);
end


% Reinsert
function reinsert(hObject,eventdata,hfig)
hpar=get(hfig,'UserData');

refufile=get(findobj(hfig,'Tag','RefufileEdit'), 'String');

reinsmode=get(findobj(hfig,'Tag','ReinsertModeMenu'), 'Value');

ind=get(findobj(hfig,'Tag','PoolList'), 'UserData');
if ~isempty(ind)
    data=get(findobj(hfig,'Tag','PoolList'), 'Data');
    asyid=data{ind,1};
    
    switch(reinsmode)
        case 1,
            figure(hpar);
            [x,y]=ginput(1);
            ldptox7(refufile,asyid,x,y);
        case 2,
            ldplow7(refufile,asyid);
        case 3,
            ldpins7(refufile,asyid);
    end
    
    update(hfig,[]);
end
end


% Refuwin closefcn
function closewin(hObject,eventdata)
    hpar=get(hObject,'UserData');
    if ishandle(hpar)
        figure(hpar);
        ccplot;
        
        figure(hObject);
    end
    closereq;
end


% Update window
function update_view(hObject,eventdata,hfig)
update(hfig,[]);
end


% Clear all operations
function clearops(hObject,eventdata,hfig)
refufile=get(findobj(hfig,'Tag','RefufileEdit'), 'String');

if exist(refufile,'file')
    freshload=[];
    shuffles=[];
    poolload=[];
    
    save(refufile,'-append','freshload','shuffles','poolload');
    
    update(hfig,[]);
end
end