#!/bin/sh
######################################
# Autotip_bilaga7_F3 v1.0
# Autotip_XP bilaga 7 F3 generator
# Underprogram till Autotip_XP.m
# Programmet har en dist fil som
# enda inparameter.
# Jan Karjalainen, FTB 2004
######################################
polut > /dev/null << END
bilaga7.txt
$1

POWER





END
