#!/bin/sh
######################################
# Autotip_bilaga8 v1.0
# Autotip_XP bilaga 8 generator
# Underprogram till Autotip_XP.m
# Programmet har en dist fil som
# enda inparameter.
# Jan Karjalainen, FTB 2004
######################################
polut > /dev/null << END
bilaga8.txt
$1

BURNUP





END
