%@(#)   ssortprint7.m 1.1	 06/03/22     09:05:50
%
%function ssortprint7(sorton,pool,lastcyclewise,prifil,matfil,basfil,test);
% 
%Sort and print primitive file (argument basfil, output file from command sshist),
%and create a MATLAB-file (argument matfil) and an ASCII-printfile (argument prifil)
%
% Adapted & modified version of the sortprint7 function for output of data as
% generated by the function sshist7.
% M. Dahlfors 04/04/16
%
%options:
%  sorton - 'crid','crtx','crtb', default='crid'
%  pool   - 'full','pool','core','clab','reuse', default='pool'
%  lastcyclewise - 0 or 1, if lastcyclewise is =1 , all bundles with the same
%                  last cycle are grouped together, default=0
%
%files:
%  prifil - Print the result in Ascii on this file, default=sorton, i.e.
%           if the result is sorted on crid, the result will be printed on crid.lis
%           If prifil is a number no printing is made.
%  basfil - Output file from program bunhist, default='utfil.mat'
%  matfil - Save the result in this file on MATLAB-format, default=same as sorton, i.e.
%           if the result is sorted on asyid, the result will be stored on crid.mat
%
%
% Example 1: ssortprint7
% Example 2: ssortprint7('crid','full')
% Example 2a: ssortprint7  crid full
% Example 3: ssortprint7('crid','pool',0,'crid.lis','crid.mat','utfil.mat')
% Example 3a: ssortprint7 crid pool 0 crid.lis crid.mat utfil.mat
% Example 4: ssortprint7('crid','burnup>30000',0,'crid.lis','crid.mat','utfil.mat')
function ssortprint7(sorton,pool,lastcyclewise,prifil,matfil,basfil);
if nargin<1, sorton='crid';end
if nargin<2, pool='pool';end
if nargin<3, lastcyclewise=0;end
if nargin<4, prifil=[remblank(sorton),'.lis'];end
if nargin<5, matfil=[remblank(sorton),'.mat'];end
if nargin<6, basfil='utfil-ss.mat';end
if isstr(lastcyclewise), lastcyclewise=str2num(lastcyclewise);end
pool=remblank(pool);
sorton=lower(sorton);sorton=remblank(sorton);
[ierr,errtext]=findss7(basfil,matfil,pool);
titel=[pool,' inventory, sorted on ',sorton];
%if ierr==0,
  load(matfil)
  isort=(1:length(ITOT));
  if strcmp(sorton,'crid'),
    [x,isort]=ascsort(right_adjust(CRID));
    isort(length(isort):-1:1)=isort;
  elseif strcmp(sorton,'crtx'),
    [x,isort]=sort(crtx);
  elseif strcmp(sorton,'crtb'),
    [x,isort]=sort(crtb);
  else
    disp('Error in ssortprint7 unknown value for argument sorton')
    ierr=2;
  end
%  if ierr==0,
    ssortfil7(matfil,matfil,isort)
    if lastcyclewise>0,
      load(matfil);
      [lc,isort]=sort(lastcyc);
      ssortfil7(matfil,matfil,isort)
      titel=[titel,' cyclewise'];
    end
    fulll=0;
    if strcmp(pool,'full'), fulll=1;end
    if isstr(prifil),
       sspristat7(matfil,prifil,titel,fulll,pool)
    end
%  end
%end
