function [d1,d2,sigr,siga1,siga2,usig1,usig2,ny,d1d,d2d,sigrd,siga1d,siga2d,usig1d,usig2d,...
    d1t,d2t,sigrt,siga1t,siga2t,usig1t,usig2t]=xs_ramcof(disfil,f_master,Pdens,Tfm,knum,kmax,ncc)
[d1,d2,sigr,siga1,siga2,usig1,usig2,ny]=...
        xsec2mstab7(disfil,f_master,Pdens,Tfm,knum);
        [d1d,d2d,sigrd,siga1d,siga2d,usig1d,usig2d]=...
        xsec2mstab7(disfil,f_master,Pdens+1,Tfm,knum);
        [d1t,d2t,sigrt,siga1t,siga2t,usig1t,usig2t]=...
        xsec2mstab7(disfil,f_master,Pdens,Tfm+1,knum);
    d1d=d1d-d1;
    d1d=d1d-d1;
    sigrd=sigrd-sigr;
    siga1d=siga1d-siga1;
    siga2d=siga2d-siga2;
    usig1d=usig1d-usig1;
    usig2d=usig2d-usig2;
    d1t=d1t-d1;
    d1t=d1t-d1;
    sigrt=sigrt-sigr;
    siga1t=siga1t-siga1;
    siga2t=siga2t-siga2;
    usig1t=usig1t-usig1;
    usig2t=usig2t-usig2;    
    ny=reshape(ny,kmax,ncc);
    d1=reshape(d1,kmax,ncc);
    d1d=reshape(d1d,kmax,ncc);
    d1t=reshape(d1t,kmax,ncc);
    d2=reshape(d2,kmax,ncc);
    d2d=reshape(d2d,kmax,ncc);
    d2t=reshape(d2t,kmax,ncc);
    sigr=reshape(sigr,kmax,ncc);
    sigrd=reshape(sigrd,kmax,ncc);
    sigrt=reshape(sigrt,kmax,ncc);
    siga1=reshape(siga1,kmax,ncc);
    siga1d=reshape(siga1d,kmax,ncc);
    siga1t=reshape(siga1t,kmax,ncc);
    siga2=reshape(siga2,kmax,ncc);
    siga2d=reshape(siga2d,kmax,ncc);
    siga2t=reshape(siga2t,kmax,ncc);
    usig1=reshape(usig1,kmax,ncc);
    usig1d=reshape(usig1d,kmax,ncc);
    usig1t=reshape(usig1t,kmax,ncc);
    usig2=reshape(usig2,kmax,ncc);
    usig2d=reshape(usig2d,kmax,ncc);
    usig2t=reshape(usig2t,kmax,ncc);